config/routes.rb
Rails.application.routes.draw do
  #pages controller action home
  root 'welcome#index'

  resources :collabs do
    member do
      get 'join'
      get 'leave'
    end
  end
  # route post/nr/comments nested route
  resources :posts do
    resources :comments
  end

  # route collab/nr/message/nr
  resources :collabs do
    resources :messages
  end

  # route posts/tag/....
  get 'tags/:tag', to: 'posts#index', as: :tag
  # route collabs/skill/....
  get 'skill/:skill', to: 'collabs#index', as: :skill


  # signup get request sned to users controlled action new
  get 'signup', to: 'users#new'
  # create all routes for users except nes as it is defined already
  resources :users, except: [:new]
  #showcase get request send to pages controller action showcase
  get 'showcase', to: 'pages#showcase'

  #login/logout routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/collab.rb
class Collab < ApplicationRecord
    acts_as_taggable_on :skills
    #validate that a title and description are present and with a min and max lengths, before saving an article
    validates :title, presence: true, length: { minimum: 5, maximum: 150}
    validates :body, presence: true, length: { minimum: 25, maximum: 1000}
    validate :validate_image_attachement

    has_many :user_collabs, :dependent => :destroy
    has_many :users, through: :user_collabs
    has_many :messages, dependent: :destroy
  

    has_one_attached :image, dependent: :destroy

    private
    def validate_image_attachement
        return unless image.attached?
  
        unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
          errors.add(:attachments ,"You can only attach .jpeg .jpg or .png files")
        end
      end


end

app/controllers/collabs_controller.rb
class CollabsController < ApplicationController
  before_action :set_collab, only: %i[ show edit update destroy join leave ]
  before_action :require_login, except: [ :index, :show ]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  # GET /collabs or /collabs.json
  def index
    # force all tags to be saved lowercase
    ActsAsTaggableOn.force_lowercase = true
    # remove all unused tag objects
    ActsAsTaggableOn.remove_unused_tags = true

    @skills = Collab.tags_on(:skills).most_used(10).order("taggings_count DESC")
    if params[:skill]
      @collabs = Collab.tagged_with(params[:skill]).paginate(page: params[:page], per_page: 12)
    else
      #potentially change to views DESC if want to show by popularity, use will_paginate gem
      @collabs = Collab.order("created_at DESC").paginate(page: params[:page], per_page: 12)
    end
  end

  # GET /collabs/1 or /collabs/1.json
  def show
  end

  # GET /collabs/new
  def new
    @collab = Collab.new
  end

  # GET /collabs/1/edit
  def edit
  end

  # POST /collabs or /collabs.json
  def create
    @collab = Collab.new(collab_params)
    @collab.owner = current_user.id
    respond_to do |format|
      if @collab.save
        UserCollab.create(user_id: current_user.id, collab_id: @collab.id)
        format.html { redirect_to collab_url(@collab), notice: "Collab was successfully created." }
        format.json { render :show, status: :created, location: @collab }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @collab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collabs/1 or /collabs/1.json
  def update
    respond_to do |format|
      if @collab.update(collab_params)
        format.html { redirect_to collab_url(@collab), notice: "Collab was successfully updated." }
        format.json { render :show, status: :ok, location: @collab }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @collab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collabs/1 or /collabs/1.json
  def destroy
    @collab.destroy
    flash[:notice] = "Your collab has been deleted."
    redirect_to collabs_path, status: :see_other
  end

  def join
    UserCollab.create(user_id: current_user.id, collab_id: @collab.id)
    flash[:notice] = "Good luck, you have joined this collab!"
    # reduce participants count by 1 when someone joins
    @collab.participants = @collab.participants - 1
    @collab.save
    redirect_to @collab
  end
  
  def leave
    user = UserCollab.find_by(user_id: current_user.id, collab_id: @collab.id)
    user.destroy
    flash[:notice] = "You have left this collab."
    @collab.participants = @collab.participants + 1
    @collab.save
    redirect_to @collab
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collab
      @collab = Collab.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def collab_params
      params.require(:collab).permit(:title, :body, :participants, :image, :owner, :skill_list)
    end

    def require_same_user
      # if current user is not the author of the collab and is not admin, then redirect
      if current_user.id != @collab.owner && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own collab projects."
        redirect_to @collab
      end
    end

end

app/helpers/collabs_helper.rb
module CollabsHelper
end

app/views/collabs/_collab.html.erb
<% @collabs.each do |collab| %>
  <% if collab.participants > 0 || logged_in? && collab.users.exists?(current_user.id) %>
    <div class="col-lg-4 col-md-6 item-container">
      <% if collab.image.attached? %>
        <%= image_tag collab.image, class: "item-img" %>
      <% else %>
        <%= image_tag "lightbulb.jpg", class: "item-img" %>
      <% end %>
      <div class="overlay">
        <div class="overlay-content">
          <%# <h5>by <%= link_to collab.user.username, user_path(collab.user) %></h5> %>
          <h3><%= collab.title %></h3>
          <p class="item-text"><%= truncate(collab.body, length:100) %></p>
          <p class="item-text">
          Skills needed: <%= raw collab.skill_list.map { |s| link_to s, skill_path(s) }.join(', ') %>
          </p>
          <%= link_to "VIEW", collab_path(collab), class: "btn btn-outline-light btn-md" %>
          <% if logged_in? && (collab.owner == current_user.id || current_user.admin?) %>
            <%= link_to "Edit", edit_collab_path(collab), class: "btn btn-outline-light btn-md" %>
            <%= button_to 'DELETE', collab_path(collab),class: "btn btn-outline-light btn-md", method: :delete %>
          <% end %> 
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/collabs/_form.html.erb
<div class="container">
    <div class="row justify-content-center text-center">
        <div class=col-8>
            <%= form_with(model: @collab, class: "shadow p-3 mb-3 bg-info") do |form| %>
              <%= render 'shared/errors', obj: @collab %>
              <div class="form-group row">
                <%= form.label :title, class: "col-1 col-form-label text-light" %>
                <%= form.text_field :title, class: "form-control shadow text-light", placeholder: "Collab title"  %>
              </div>

              <div class="form-group row">
                <%= form.label :body, class: "col-1 col-form-label text-light" %>
                <%= form.text_area :body, rows: 10, class: "form-control shadow text-light", placeholder: "Collab description" %>
              </div>

              <div class="form-group row">
                <%= form.label :skill_list, "Skills", class: "col-1 col-form-label text-light" %>
                <%= form.text_field :skill_list, class: "form-control shadow text-light", value: @collab.skill_list.join(","), placeholder: "Skills (separated by commas)"  %>
              </div>

              <div class="form-group row">
                <%= form.label :participants, "Nr of participants", class: "col-1 col-form-label text-light" %>
                <%= form.number_field :participants,  in: 1.0..20.0, step: 1.0, class: "form-control shadow text-light", placeholder: "How many people in collab?"  %>
              </div>

              <div class="form-group mb-3 row justify-content-center text-center">
                  <div class="col-8">
                      <%= form.file_field :image, direct_upload: true %>
                  </div>
              </div>

              <div>
                <%= form.submit value="Create collab", class: "btn btn-md btn-form"%>
              </div>
            <% end %>
        </div>
        <%= link_to 'Cancel and return to collabs page', collabs_path, class: "text-muted" %>
    </div>
</div> 

app/views/collabs/edit.html.erb
<h1>Editing collab</h1>

<%= render "form", collab: @collab %>

<br>

<div>
  <%= link_to "Show this collab", @collab %> |
  <%= link_to "Back to collabs", collabs_path %>
</div>

app/views/collabs/index.html.erb
<h1>All collabs</h1>

<% @skills.each do |skill| %>
<h1><%= link_to skill, "/skill/#{skill}" %></h1>
<% end %> 

<div class="flickr_pagination">
  <%= will_paginate @collabs, :container => false %>
</div>

<div class="container">
  <div class="row justify-content-center">
    <%= render 'collab' %>
  </div>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @collabs, :container => false %>
</div>

app/views/collabs/new.html.erb
<h1>Add your collab!</h1>

<%= render "form" %>

<br>

app/views/collabs/show.html.erb
<div class="imgContainer">
    <% if @collab.image.attached? %>
      <%= image_tag @collab.image, class: "card-img-top img-fluid full-img" %>
    <% else %>
      <%= image_tag "lightbulb.jpg", class: "card-img-top full-img" %>
    <% end %>
  <div class="overlay"></div>
</div>

<h5 class="card-title mt-2"><%= @collab.title %></h5>
<p class="card-text"><%= truncate(@collab.body, length:100) %></p>

<% if logged_in? && (@collab.owner == current_user.id || current_user.admin?) %>
  <%= link_to "Edit", edit_collab_path(@collab), class: "btn btn-outline-light btn-md" %>
  <%= button_to 'DELETE', collab_path(@collab),class: "btn btn-outline-light btn-md", method: :delete %>
<% end %>

<% if logged_in? %>
  <% if @collab.owner != current_user.id %>
    <% if is_member? %> 
      <%= link_to 'leave', leave_collab_path(@collab), class: "btn btn-outline-light btn-md" %>
    <% else %>
      <%= link_to 'join', join_collab_path(@collab), class: "btn btn-outline-light btn-md" %>
    <% end %>
  <% end %>
<% end %>


<% if logged_in? && @collab.users.exists?(current_user.id) %>
  <h3>Chat</h3>
  <%= render partial: "messages/form", locals: { collab: @collab, parent: nil } %>
  <%# to improve performance do eager loading for user to preload data into memory instead of multiple request to database .includes(:user) %>
  <%= render @collab.messages.where(parent_id: nil).includes(:user).order(id: :desc) %>
<% end %>

<div>
  <%= link_to "Back to all collabs", collabs_path %>
</div>