config/routes.rb
Rails.application.routes.draw do
  #pages controller action home
  root 'welcome#index'

  resources :collabs do
    member do
      get 'join'
      get 'leave'
    end
  end
  # route post/nr/comments nested route
  resources :posts do
    resources :comments
  end

  # route collab/nr/message/nr
  resources :collabs do
    resources :messages
  end

  # route posts/tag/....
  get 'tags/:tag', to: 'posts#index', as: :tag
  # route collabs/skill/....
  get 'skill/:skill', to: 'collabs#index', as: :skill


  # signup get request sned to users controlled action new
  get 'signup', to: 'users#new'
  # create all routes for users except nes as it is defined already
  resources :users, except: [:new]
  #showcase get request send to pages controller action showcase
  get 'showcase', to: 'pages#showcase'

  #login/logout routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @posts = Post.where(:created_at =>(Date.today - 35.days)..Date.today).order('views desc').limit(3)
        @collabs = Collab.order("created_at DESC").limit(3)
    end 
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_carousel.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-interval="7000">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
            aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
            aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner" role="listbox">
        <!-- Slide 1 -->
        <div class="carousel-item active" id="slide1">
            <div class="carousel-overlay"></div>
            <div class="carousel-caption text-center">
                <h1>CREATE</h1>
                <h3>A space for your creative magic to happen!</h3>
                <%= link_to "Sign up!", signup_path, class:"btn btn-lg btn-header" %>
            </div>
        </div>
        <!-- Slide 2 -->
        <div class="carousel-item" id="slide2">
            <div class="carousel-overlay"></div>
            <div class="carousel-caption text-center">
                <h1>SHOWCASE</h1>
                <h3>See what others do and show us what you are proud of!</h3>
                <%= link_to "Browse projects", posts_path, class:"btn btn-lg btn-header" %>
            </div>
        </div>
        <!-- Slide 3 -->
        <div class="carousel-item" id="slide3">
            <div class="carousel-overlay"></div>
            <div class="carousel-caption text-center">
                <h1>COLLABORATE</h1>
                <h3>Find your tribe and achieve great things together!</h3>
                <%= link_to "Join collab", collabs_path, class:"btn btn-lg btn-header" %>
            </div>
        </div>
    </div>
</div>

app/views/welcome/_collab.html.erb
<% @collabs.each do |collab| %>
    <% if collab.participants > 0 || logged_in? && collab.users.exists?(current_user.id) %>
        <div class="col-lg-4 col-md-6 item-container">
        <div class="backdrop"></div>
            <% if collab.image.attached? %>
                <%= image_tag collab.image, class: "item-img" %>
            <% else %>
                <%= image_tag "lightbulb2.jpg", class: "item-img" %>
            <% end %>
        <div class="overlay">
            <div class="overlay-content">
            <h4><%= collab.title %></h4>
            <p class="item-text"><%= truncate(collab.body, length:100) %></p>
            <p class="item-text">
            Skills needed: <%= raw collab.skill_list.map { |s| link_to s, skill_path(s) }.join(', ') %>
            </p>
            <%= link_to "VIEW", collab_path(collab), class: "btn btn-outline-light btn-md" %>
            <% if logged_in? && (collab.owner == current_user.id || current_user.admin?) %>
                <%= link_to "Edit", edit_collab_path(collab), class: "btn btn-outline-light btn-md" %>
                <%= button_to 'DELETE', collab_path(collab),class: "btn btn-outline-light btn-md", method: :delete %>
            <% end %> 
            </div>
        </div>
        </div>
    <% end %>
<% end %>

app/views/welcome/_post.html.erb
<% @posts.each do |post| %>
    <div class="col-lg-4 col-md-6 item-container">
    <% if post.image.attached? %>
        <%= image_tag post.image, class: "item-img" %>
    <% else %>
        <%= image_tag "lightbulb2.jpg", class: "item-img" %>
    <% end %>
    <div class="overlay">
        <div class="overlay-content">
        <h5>by <%= link_to post.user.username, user_path(post.user) %></h5>
        <h4><%= post.title %></h4>
        <p class="item-text"><%= truncate(post.body, length:100) %></p>
        <p class="item-text">
            Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
        </p>
        <%= link_to "VIEW", post_path(post), class: "btn btn-outline-light btn-md" %>
        </div>
    </div>     
    </div>
<%end%> 

app/views/welcome/index.html.erb
<body>
    <header>
        <%= render 'carousel' %>
    </header>
    <main>     
        <div class="container">
            <H2> FEATURED PROJECT </H2>
            <H5>Here goes text describing what this section is all about. Here goes text describing what this section is all about.  Here goes text describing what this  section is all about. </H5>
            <div class="row justify-content-center mt-4">
                <%= render 'post' %>
            </div>
            <H2> NEW COLLABS </H2>
            <H5>Here goes text describing what this section is all about. Here goes text describing what this section is all about.  Here goes text describing what this  section is all about. </H5>
            <div class="row justify-content-center mt-4">
                <%= render 'collab' %>
            </div>
        </div>
    </main>
</body>