config/routes.rb
Rails.application.routes.draw do
  #pages controller action home
  root 'welcome#index'

  resources :collabs do
    member do
      get 'join'
      get 'leave'
    end
  end
  # route post/nr/comments nested route
  resources :posts do
    resources :comments
  end

  # route collab/nr/message/nr
  resources :collabs do
    resources :messages
  end

  # route posts/tag/....
  get 'tags/:tag', to: 'posts#index', as: :tag
  # route collabs/skill/....
  get 'skill/:skill', to: 'collabs#index', as: :skill


  # signup get request sned to users controlled action new
  get 'signup', to: 'users#new'
  # create all routes for users except nes as it is defined already
  resources :users, except: [:new]
  #showcase get request send to pages controller action showcase
  get 'showcase', to: 'pages#showcase'

  #login/logout routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
    # create association between post and a single user
    belongs_to :user
    has_many :comments, dependent: :destroy

    acts_as_taggable_on :tags
    acts_as_votable
    
    #validate that a title and description are present and with a min and max lengths, before saving the post
    validates :title, presence: true, length: { minimum: 5, maximum: 150}
    validates :body, presence: true, length: { minimum: 25, maximum: 1000}
    validate :validate_image_attachement

    has_one_attached :image, dependent: :destroy
    private

    def validate_image_attachement
      return unless image.attached?

      unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
        errors.add(:attachments ,"You can only attach .jpeg .jpg or .png files")
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy]
  # call require_login before all actions except index and show
  before_action :require_login, except: [ :index, :show]
  # call require_same_user to check that the logged in user is also the author of the post
  before_action :require_same_user, only: [:edit, :update, :destroy]


  # GET /posts or /posts.json
  def index
    # force all tags to be saved lowercase
    ActsAsTaggableOn.force_lowercase = true
    # remove all unused tag objects
    ActsAsTaggableOn.remove_unused_tags = true
    
    @tags = Post.tags_on(:tags).most_used(10).order("taggings_count DESC")
    # @tags = ActsAsTaggableOn::Tag
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 12)
    else
      #potentially change to views DESC if want to show by popularity, use will_paginate gem
      @posts = Post.order("created_at DESC").paginate(page: params[:page], per_page: 12)
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    # incrments view by 1 when more button is pressed
    @post.views = @post.views + 1
    @post.save
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    # assign current_user 
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    flash[:notice] = "Your posts has been deleted."
    redirect_to posts_path, status: :see_other
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :link, :views, :tag_list, :image)
    end

    def require_same_user
      # if current user is not the author of the post and is not admin, then redirect
      if current_user != @post.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own project post."
        redirect_to @post
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container">
    <div class="row justify-content-center text-center">
        <div class=col-8>
            <%= form_with(model: post, class: "shadow p-3 mb-3 bg-info") do |form| %>
              <%= render 'shared/errors', obj: @post %>
              <div class="form-group row">
                <%= form.label :title, class: "col-1 col-form-label text-light" %>
                <%= form.text_field :title, class: "form-control shadow text-light", placeholder: "Project title"  %>
              </div>

              <div class="form-group row">
                <%= form.label :body, class: "col-1 col-form-label text-light" %>
                <%= form.text_area :body, rows: 10, class: "form-control shadow text-light", placeholder: "Project description" %>
              </div>

              <div class="form-group row">
                <%= form.label :tag_list, "Tags", class: "col-1 col-form-label text-light" %>
                <%= form.text_field :tag_list, class: "form-control shadow text-light", value: @post.tag_list.join(","), placeholder: "Tags (separated by commas)"  %>
              </div>

              <div class="form-group row">
                <%= form.label :link, "Link", class: "col-1 col-form-label text-light" %>
                <%= form.text_field :link, class: "form-control shadow text-light", placeholder: "Add link to a tutorial"  %>
              </div>

              <div class="form-group mb-3 row justify-content-center text-center">
                  <div class="col-8">
                      <%= form.file_field :image, direct_upload: true %>
                  </div>
              </div>

              <div>
                <%= form.submit value="Add project", class: "btn btn-md btn-form"%>
              </div>
            <% end %>
        </div>
        <%= link_to 'Cancel and return to project showcase', posts_path, class: "text-muted" %>
    </div>
</div> 

app/views/posts/_header.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel" data-interval="7000">
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item" id="featuredProject">
            <div class="carousel-overlay"></div>
            <div class="carousel-caption text-center">
                <h1>FEATURED PROJECT</h1>
                <h3>This week's featured project info</h3>
                <%= link_to "CHECK-OUT!", signup_path, class:"btn btn-lg btn-header" %>
            </div>
        </div>
    </div>
</div>

app/views/posts/_post.html.erb
<% @posts.each do |post| %>
  <div class="col-lg-4 col-md-6 item-container">
    <% if post.image.attached? %>
      <%= image_tag post.image, class: "item-img" %>
    <% else %>
      <%= image_tag "key.png", class: "item-img" %>
    <% end %>
    <div class="overlay">
      <div class="overlay-content">
        <h5>by <%= link_to post.user.username, user_path(post.user) %></h5>
        <h3><%= post.title %></h3>
        <p class="item-text"><%= truncate(post.body, length:100) %></p>
        <p class="item-text">
          Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
        </p>
        <%= link_to "VIEW", post_path(post), class: "btn btn-outline-light btn-md" %>
      </div>
    </div>     
  </div>
<%end%>

app/views/posts/edit.html.erb
<h1>Edit project info</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this project", @post %> |
  <%= link_to "Back to project showcase", posts_path %>
</div>

app/views/posts/index.html.erb
<body>
    <header>
        <%= render 'header' %>
    </header>
    <main>
      <div class="container">
        <h2>PROJECT SHOWCASE</h2>
        <H5>Here goes text describing what this section is all about. Here goes text describing what this section is all about.  Here goes text describing what this  section is all about. </H5>

        <h4>POPULAR TAGS:
        <% @tags.each do |tag| %>
        <%= link_to tag, "/tags/#{tag}" %>
        <% end %> 
        </h4>
        <div class="row justify-content-center">
          <%= render 'post' %>
        </div>
        <div class="flickr_pagination mb-4">
          <%= will_paginate @posts, :container => false %>
        </div>
      </div>
    </main>
</body>

app/views/posts/new.html.erb
<h1>Add your project</h1>

<%= render "form", post: @post %>

<br>

app/views/posts/show.html.erb
<div class="container">
      <div class="row justify-content-center">
          <div class="col-md-8 mt-4">
              <div class="card text-center shadow mb-5">
                <div class="card-header">
                    <% if @post.user.image.attached? %>
                      <%= link_to image_tag(@post.user.image, style:"width:50px; height:50px; border-radius:100%;", class: "mx-auto d-block"), user_path(@post.user)%>
                      by <%= @post.user.username %>
                    <% else %>
                      <%= image_tag "default_profile.png", style:"width:50px; height:50px; border-radius:100%;", class: "mx-auto d-block" %>
                    <% end %> 
                </div>
              <div class="card-body">
                  <div class="imgContainer">
                      <% if @post.image.attached? %>
                        <%= image_tag @post.image, class: "card-img-top img-fluid full-img" %>
                      <% else %>
                        <%= image_tag "default_profile.png", class: "card-img-top full-img" %>
                      <% end %>
                      <div class="overlay"></div>
                  </div>
                  <h5 class="card-title mt-2"><%= @post.title %></h5>
                  <p class="card-text"><%= @post.body %></p>
                  <% if logged_in? && ( @post.user == current_user || current_user.admin? ) %>
                    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-outline-light btn-md" %>
                    <%= button_to 'DELETE', post_path(@post),class: "btn btn-outline-light btn-md", method: :delete %>
                  <% end %>
                  <p>
                    Tags: <%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
                  </p>
                  <h5 class="card-title mt-2"> Views: <%= @post.views %></h5>
                  <h5 class="card-title mt-2"> Link to tutorial: <%= @post.link %></h5>
              </div>
              <div class="card-footer text-muted">
                  <small>Created <%= time_ago_in_words(@post.created_at) %> ago</small>
              </div>
          </div>
          <div>
          <h3>Comments</h3>
          <%= render partial: "comments/form", locals: { post: @post, parent: nil } %>
          <%# to improve performance do eager loading for user to preload data into memory instead of multiple request to database .includes(:user) %>
          <%= render @post.comments.where(parent_id: nil).includes(:user).order(id: :desc) %>
          <%= link_to "Back to project showcase", posts_path %>
          </div>
      </div>
</div>