config/routes.rb
Rails.application.routes.draw do
  #pages controller action home
  root 'welcome#index'

  resources :collabs do
    member do
      get 'join'
      get 'leave'
    end
  end
  # route post/nr/comments nested route
  resources :posts do
    resources :comments
  end

  # route collab/nr/message/nr
  resources :collabs do
    resources :messages
  end

  # route posts/tag/....
  get 'tags/:tag', to: 'posts#index', as: :tag
  # route collabs/skill/....
  get 'skill/:skill', to: 'collabs#index', as: :skill


  # signup get request sned to users controlled action new
  get 'signup', to: 'users#new'
  # create all routes for users except nes as it is defined already
  resources :users, except: [:new]
  #showcase get request send to pages controller action showcase
  get 'showcase', to: 'pages#showcase'

  #login/logout routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_msg.html.erb
<%# display message on successfully saving new article %>
<% flash.each do |notice, flash_msg|%>
   <h3><%= flash_msg %></h3>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- Start of Navigation bar -->
<nav class="navbar mb-5 navbar-expand-lg navbar-dark fixed-top" id="full-nav">
    <div class="container-sm">
        <a href="#"></a>
        <button class="navbar-toggler ms-auto" data-bs-toggle="collapse" data-bs-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse ms-auto" id="navbar">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item ms-auto">
                    <%= link_to "HOME", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">SHOWCASE</a>
                    <ul class="dropdown-menu" id="dropdown-menu1" aria-labelledby="navbarDropdown">
                        <% if logged_in?%>
                          <li><%= link_to "ADD PROJECT", new_post_path, class:"dropdown-item "  %></li>
                          <% end %>
                          <li><%= link_to "ALL PROJECTS", posts_path, class:"dropdown-item"  %></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">COLLABS</a>
                    <ul class="dropdown-menu" id="dropdown-menu2" aria-labelledby="navbarDropdown">
                        <% if logged_in?%>
                          <li><%= link_to "ADD COLLAB", new_collab_path, class:"dropdown-item "  %></li>
                          <% end %>
                          <li><%= link_to "ALL COLLABS", collabs_path, class:"dropdown-item"  %></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <% if logged_in?%>
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          <%= "(Admin)" if current_user.admin? %>
                          <%= current_user.username %>
                        </a>
                    <% else %>
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> <%= image_tag "user.png", style:"width:30px; height:30px; border-radius:100%;", class: "ms-auto" %></a>
                    <% end %>
                    <ul class="dropdown-menu" id="dropdown-menu3" aria-labelledby="navbarDropdown">
                        <% if logged_in?%>
                          <li><%= link_to "PROFILE INFO", user_path(current_user), class:"dropdown-item" %></li>
                          <li><%= button_to "LOGOUT", logout_path, class:"dropdown-item", method: :delete, data: {turbo: :false} %></li>
                        <% else %>
                          <li><%= link_to "LOGIN", login_path, class:"dropdown-item" %></li>
                          <li><%= link_to "SIGN-UP", signup_path, class:"dropdown-item" %></li>
                        <% end %>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- End of Navigation bar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;500;800&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar'%>
    </header>
    <main>
      <%= render 'layouts/msg' %>
      <%= yield %>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>